### PR TITLE
Fixed issue with 0000 being a valid year.

### PR DESCRIPTION
**Pull request by Teyler7**
It is litterally a simple if statement.

### CODE REVIEW

**Comment by matthewnitschke** [comment]
Not a huge fan of a case statement like that, also technically 0000 is a valid year, just not one that anyone would ever put in.

Is this actually an issue? like has a user tried to enter it?

**Comment by Teyler7** [comment]
Yes this is an issue that has happened more than a couple of times. I was trying to think of a better way than a case statement from the year, but that is the only case where date can break. I even thought of having 0000 become 2000 if entered, but I felt like that goes outside of the scope of what Kavie is meant to do. 

My logic was in the rare case that a user enters 0000, we should let them know it isn't a valid date and they should realize that 0000 isn't valid and change it to 2000. In the case of the website that I have implemented Kavie date validation, there is text masking in place, so 0000 is probably entered in as more of an accident than on purpose and alerting the user might even prevent a false date being submitting.

What are your thoughts?

**Comment by matthewnitschke** [comment]
Hm. well, I would prefer a 
```
parseInt(year) <= 0
```
this just catches more than static 0000 characters

**Comment by matthewnitschke** [comment]
also it should be noted that `year` is a string not an int. So with your if statement you are relying on JavaScript 's type inference which is not ideal

**Comment by Teyler7** [comment]
Ah that makes sense. Tested that solution, issue with that is it allows years such as 0001 to be valid.

**Comment by matthewnitschke** [comment]
you are getting to the point that you are trying to create a case statement for everything. to a certain point you just have to say please don't be stupid users

**Comment by Teyler7** [comment]
Hahaha that is very true. Feel free to close the merge if you please :)

**Pull request merged**
